clusters:
- name: openshift
  destinationServer: https://api.cluster-p5fbr.p5fbr.sandbox3063.opentlc.com:6443
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

#- name: gke
#  destinationServer: #INSERT MASTERIP HERE
#  apps:
#    prometheus:
#      enabled: true
#      version: "9.7.4"
#    sampleApp:
#      enabled: true
#      branch: HEAD
